---
version: '3'
services:
  soundboard:
    container_name: soundboard
    build: .
    devices:
      - "/dev/snd:/dev/snd"
      - "/sys:/sys"
    environment:
      - ALSA_CARD:${SOUND_DEVICE:-PCH} #configurable in .env file
    restart: unless-stopped
