name: Code coverage
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
    - name: Generate coverage report
      run: make coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.12
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        # TODO remove coverage.xml
        #file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
